{{- if .Values.opa.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pysetu.fullname" . }}-opa-policies
  labels:
    {{- $ctx := dict "component" "opa" "Values" .Values "Chart" .Chart "Release" .Release }}
    {{- include "pysetu.componentLabels" $ctx | nindent 4 }}
data:
  gateway.rego: |
{{ .Files.Get "files/gateway.rego" | indent 4 }}
{{- end }}
