"""domain allowlists

Revision ID: 034_domain_allowlists
Revises: 033_tenant_rate_limits
Create Date: 2026-08-11 18:28:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '034_domain_allowlists'
down_revision: Union[str, None] = '033_tenant_rate_limits'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('allowed_login_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tenants', sa.Column('allowed_api_origins', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'allowed_api_origins')
    op.drop_column('tenants', 'allowed_login_domains')
    # ### end Alembic commands ###
