"""approval_requests_mcp_tools

Revision ID: 078_mcp_tools
Revises: 077_mcp_access_request
Create Date: 2026-08-24 14:19:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '078_mcp_tools'
down_revision: Union[str, None] = '077_mcp_access_request'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_requests', sa.Column('requested_mcp_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approval_requests', 'requested_mcp_tools')
    # ### end Alembic commands ###
