{{- if .Values.opa.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helixguard.fullname" . }}-opa
  labels:
    {{- $ctx := dict "component" "opa" "Values" .Values "Chart" .Chart "Release" .Release }}
    {{- include "helixguard.componentLabels" $ctx | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8181
      targetPort: http
  selector:
    {{- $ctx := dict "component" "opa" "Values" .Values "Chart" .Chart "Release" .Release }}
    {{- include "helixguard.componentSelectorLabels" $ctx | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helixguard.fullname" . }}-opa
  labels:
    {{- $ctx := dict "component" "opa" "Values" .Values "Chart" .Chart "Release" .Release }}
    {{- include "helixguard.componentLabels" $ctx | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- $ctx := dict "component" "opa" "Values" .Values "Chart" .Chart "Release" .Release }}
      {{- include "helixguard.componentSelectorLabels" $ctx | nindent 6 }}
  template:
    metadata:
      labels:
        {{- $ctx := dict "component" "opa" "Values" .Values "Chart" .Chart "Release" .Release }}
        {{- include "helixguard.componentSelectorLabels" $ctx | nindent 8 }}
    spec:
      containers:
        - name: opa
          image: "{{ .Values.opa.image.repository }}:{{ .Values.opa.image.tag }}"
          imagePullPolicy: {{ .Values.opa.image.pullPolicy }}
          args:
            - run
            - --server
            - --log-level=info
            - /policies
          ports:
            - name: http
              containerPort: 8181
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.opa.resources | nindent 12 }}
          volumeMounts:
            - name: policies
              mountPath: /policies
              readOnly: true
      volumes:
        - name: policies
          configMap:
            name: {{ include "helixguard.fullname" . }}-opa-policies
{{- end }}
